// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("FSharp.Editing.Tests")>]
[<assembly: AssemblyTitleAttribute("FSharp.Editing")>]
[<assembly: AssemblyProductAttribute("FSharpVSPowerTools")>]
[<assembly: AssemblyDescriptionAttribute("A collection of additional commands for F# in Visual Studio")>]
[<assembly: AssemblyVersionAttribute("2.5.5")>]
[<assembly: AssemblyFileVersionAttribute("2.5.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "FSharp.Editing.Tests"
    let [<Literal>] AssemblyTitle = "FSharp.Editing"
    let [<Literal>] AssemblyProduct = "FSharpVSPowerTools"
    let [<Literal>] AssemblyDescription = "A collection of additional commands for F# in Visual Studio"
    let [<Literal>] AssemblyVersion = "2.5.5"
    let [<Literal>] AssemblyFileVersion = "2.5.5"
