// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("FSharp.Editing.VisualStudio.Tests")>]
[<assembly: AssemblyTitleAttribute("FSharp.Editing.VisualStudio.v2015")>]
[<assembly: AssemblyProductAttribute("FSharpVSPowerTools")>]
[<assembly: AssemblyDescriptionAttribute("A collection of additional commands for F# in Visual Studio")>]
[<assembly: AssemblyVersionAttribute("2.5.2")>]
[<assembly: AssemblyFileVersionAttribute("2.5.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "FSharp.Editing.VisualStudio.Tests"
    let [<Literal>] AssemblyTitle = "FSharp.Editing.VisualStudio.v2015"
    let [<Literal>] Version = "2.5.2"
    let [<Literal>] InformationalVersion = "2.5.2"
    let [<Literal>] AssemblyProduct = "FSharpVSPowerTools"
    let [<Literal>] AssemblyDescription = "A collection of additional commands for F# in Visual Studio"
    let [<Literal>] AssemblyVersion = "2.6.0"
    let [<Literal>] AssemblyFileVersion = "2.6.0"
