// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleToAttribute("FSharpVSPowerTools.Tests")]
[assembly: AssemblyTitleAttribute("FSharpVSPowerTools")]
[assembly: AssemblyProductAttribute("FSharpVSPowerTools")]
[assembly: AssemblyDescriptionAttribute("A collection of additional commands for F# in Visual Studio")]
[assembly: AssemblyVersionAttribute("1.6.1")]
[assembly: AssemblyFileVersionAttribute("1.6.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.6.1";
    }
}
