module FSharpVSPowerTools.Keywords

let keywordNames = 
   ["abstract"
    "and"        
    "as"         
    "assert"     
    "asr"     
    "base"       
    "begin"      
    "class"      
    "const"      
    "default"    
    "delegate"   
    "do"         
    "done"       
    "downcast"   
    "downto"     
    "elif"       
    "else"       
    "end"        
    "exception"  
    "extern"     
    "false"      
    "finally"    
    "for"        
    "fun"        
    "function"   
    "global"     
    "if"         
    "in"         
    "inherit"    
    "inline"     
    "interface"  
    "internal"   
    "land"      
    "lazy"      
    "let"       
    "lor"       
    "lsl"       
    "lsr"       
    "lxor"      
    "match"     
    "member"    
    "mod"       
    "module"    
    "mutable"   
    "namespace" 
    "new"       
    "null"       
    "of"         
    "open"       
    "or"         
    "override"   
    "private"    
    "public"     
    "rec"        
    "return"     
    "sig"        
    "static"     
    "struct"     
    "then"       
    "to"         
    "true"       
    "try"        
    "type"       
    "upcast"     
    "use"        
    "val"        
    "void"       
    "when"       
    "while"      
    "with"       
    "yield"      
    "_"          
    "__token_OBLOCKSEP" 
    "__token_OWITH"     
    "__token_ODECLEND"  
    "__token_OTHEN"     
    "__token_OELSE"     
    "__token_OEND"      
    "__token_ODO"       
    "__token_OLET"      
    "__token_constraint"
    "atomic"; "break"; 
    "checked"; "component"; "constraint"; "constructor"; "continue"; 
    "eager"; 
    "fixed"; "fori"; "functor"; 
    "include";  
    "measure"; "method"; "mixin"; 
    "object"; 
    "parallel"; "params";  "process"; "protected"; "pure"; 
    "recursive"; 
    "sealed"; 
    "trait";  "tailcall";
    "virtual"; "volatile" ]